(function () {
    var boardFiles = [], listData = [];
    function loadLayout() { $.ajax({method:'GET',url:'header.html',async:false,dataType:'html'}).done(function(h){$('#header').append(h);}); $.ajax({method:'GET',url:'footer.html',async:false,dataType:'html'}).done(function(h){$('#footer').append(h);new Swiper('.related-sites-swiper',{slidesPerView:5,slidesPerGroup:1,loop:true,speed:700,autoplay:{delay:2500,disableOnInteraction:false,pauseOnMouseEnter:true},observer:true,observeParents:true});}); }
    function titleFromFile(name) { return name.replace(/\.txt$/i, ''); }
    function loadNames() { return fetch('board-library/file-list.txt?t='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error();return r.text();}).then(function(text){boardFiles=text.split(/\r?\n/).map(function(n){return n.trim();}).filter(function(n){return n&&n.toLowerCase().endsWith('.txt');});var saved=new URLSearchParams(location.search).get('saved');if(saved&&saved.toLowerCase().endsWith('.txt')&&boardFiles.indexOf(saved)<0)boardFiles.unshift(saved);return boardFiles;}); }
    function loadItem(fileName) { return fetch('board-library/'+encodeURIComponent(fileName)+'?t='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error();return r.json();}).then(function(d){return{fileName:fileName,title:d.title||titleFromFile(fileName),date:d.date||'',id:Number(d.id)||0};}).catch(function(){return null;}); }
    function renderList(filter) { var target=document.getElementById('library-list');if(!target)return;var word=(filter||'').trim().toLowerCase();var rows=listData.filter(function(x){return x.title.toLowerCase().indexOf(word)>-1;});document.getElementById('library-count').textContent=rows.length;target.innerHTML=rows.map(function(x,i){return '<tr><td>'+(rows.length-i)+'</td><td class="title"><span class="law-badge library-badge">자료</span> <a href="board-library-view.html?file='+encodeURIComponent(x.fileName)+'">'+x.title+'</a></td><td>'+x.date+'</td></tr>';}).join('')||'<tr><td colspan="3">검색 결과가 없습니다.</td></tr>'; }
    function loadList() { if(!document.getElementById('library-list'))return;loadNames().then(function(files){return Promise.all(files.map(loadItem));}).then(function(items){items=items.filter(Boolean);try{var recent=JSON.parse(localStorage.getItem('kmei-library-last-saved')||'null');if(recent&&!items.some(function(x){return x.fileName===recent.fileName;}))items.push(recent);}catch(ignore){}items.sort(function(a,b){return(Number(b.id)||0)-(Number(a.id)||0);});listData=items;renderList('');}).catch(function(){document.getElementById('library-list').innerHTML='<tr><td colspan="3">자료실 목록을 불러오지 못했습니다.</td></tr>';}); }
    function renderView(item) { document.title=titleFromFile(item.fileName)+' | 경남경영경제연구원';document.getElementById('view-title').textContent=item.title||titleFromFile(item.fileName);document.getElementById('view-date').textContent=item.date;document.getElementById('view-body').innerHTML=item.content.map(function(s){var entries=s.items&&s.items.length?'<ul>'+s.items.map(function(t){return'<li>'+t+'</li>';}).join('')+'</ul>':'';return'<h4>'+s.heading+'</h4><p>'+s.text+'</p>'+entries;}).join('');var box=document.querySelector('.law-file'),area=document.getElementById('library-files');if(item.files&&item.files.length){area.innerHTML=item.files.map(function(f){return'<a href="library-file/'+encodeURIComponent(f.path)+'" download="'+f.name+'">'+f.name+' <small>('+f.size+')</small></a>';}).join('');}else if(box){box.style.display='none';} }
    function loadView() { if(!document.getElementById('library-view'))return;var requested=new URLSearchParams(location.search).get('file');loadNames().then(function(files){var fileName=files.indexOf(requested)>-1?requested:files[0];if(!fileName)throw new Error();return fetch('board-library/'+encodeURIComponent(fileName)+'?t='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error();return r.json();}).then(function(d){d.fileName=fileName;return d;});}).then(renderView).catch(function(){document.getElementById('library-view').innerHTML='<div style="padding:40px;text-align:center">자료 내용을 불러오지 못했습니다.</div>';}); }
    document.addEventListener('DOMContentLoaded',function(){loadLayout();loadList();loadView();var form=document.getElementById('library-search');if(form)form.addEventListener('submit',function(e){e.preventDefault();renderList(document.getElementById('library-keyword').value);});});
}());
